//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Services.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public class VoiceEntry implements java.lang.Cloneable,
                                   java.io.Serializable
{
    public String type;

    public String scope;

    public String sender;

    public String recipient;

    public String group;

    public String audioFile;

    public VoiceEntry()
    {
        this.type = "";
        this.scope = "";
        this.sender = "";
        this.recipient = "";
        this.group = "";
        this.audioFile = "";
    }

    public VoiceEntry(String type, String scope, String sender, String recipient, String group, String audioFile)
    {
        this.type = type;
        this.scope = scope;
        this.sender = sender;
        this.recipient = recipient;
        this.group = group;
        this.audioFile = audioFile;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        VoiceEntry r = null;
        if(rhs instanceof VoiceEntry)
        {
            r = (VoiceEntry)rhs;
        }

        if(r != null)
        {
            if(this.type != r.type)
            {
                if(this.type == null || r.type == null || !this.type.equals(r.type))
                {
                    return false;
                }
            }
            if(this.scope != r.scope)
            {
                if(this.scope == null || r.scope == null || !this.scope.equals(r.scope))
                {
                    return false;
                }
            }
            if(this.sender != r.sender)
            {
                if(this.sender == null || r.sender == null || !this.sender.equals(r.sender))
                {
                    return false;
                }
            }
            if(this.recipient != r.recipient)
            {
                if(this.recipient == null || r.recipient == null || !this.recipient.equals(r.recipient))
                {
                    return false;
                }
            }
            if(this.group != r.group)
            {
                if(this.group == null || r.group == null || !this.group.equals(r.group))
                {
                    return false;
                }
            }
            if(this.audioFile != r.audioFile)
            {
                if(this.audioFile == null || r.audioFile == null || !this.audioFile.equals(r.audioFile))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Chat::VoiceEntry");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, type);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, scope);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, sender);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, recipient);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, group);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, audioFile);
        return h_;
    }

    public VoiceEntry clone()
    {
        VoiceEntry c = null;
        try
        {
            c = (VoiceEntry)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.type);
        ostr.writeString(this.scope);
        ostr.writeString(this.sender);
        ostr.writeString(this.recipient);
        ostr.writeString(this.group);
        ostr.writeString(this.audioFile);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.type = istr.readString();
        this.scope = istr.readString();
        this.sender = istr.readString();
        this.recipient = istr.readString();
        this.group = istr.readString();
        this.audioFile = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, VoiceEntry v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public VoiceEntry ice_read(com.zeroc.Ice.InputStream istr)
    {
        VoiceEntry v = new VoiceEntry();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<VoiceEntry> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, VoiceEntry v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<VoiceEntry> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(VoiceEntry.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final VoiceEntry _nullMarshalValue = new VoiceEntry();

    /** @hidden */
    public static final long serialVersionUID = 1386349146L;
}
